// Generated by Dagger (https://dagger.dev).
package com.simtop.chart.presentation.chart;

import androidx.lifecycle.ViewModelProvider;
import dagger.MembersInjector;
import dagger.internal.InjectedFieldSignature;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class ChartFragment_MembersInjector implements MembersInjector<ChartFragment> {
  private final Provider<ViewModelProvider.Factory> viewModelFactoryProvider;

  public ChartFragment_MembersInjector(
      Provider<ViewModelProvider.Factory> viewModelFactoryProvider) {
    this.viewModelFactoryProvider = viewModelFactoryProvider;
  }

  public static MembersInjector<ChartFragment> create(
      Provider<ViewModelProvider.Factory> viewModelFactoryProvider) {
    return new ChartFragment_MembersInjector(viewModelFactoryProvider);
  }

  @Override
  public void injectMembers(ChartFragment instance) {
    injectViewModelFactory(instance, viewModelFactoryProvider.get());
  }

  @InjectedFieldSignature("com.simtop.chart.presentation.chart.ChartFragment.viewModelFactory")
  public static void injectViewModelFactory(ChartFragment instance,
      ViewModelProvider.Factory viewModelFactory) {
    instance.viewModelFactory = viewModelFactory;
  }
}
